[workspace]
resolver = "2"
members = [
   "RsIskraMeter",
   "RsPaymentTerminal",
   "rust_examples/RsExample",
   "rust_examples/RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/qwello/everest-framework.git", rev = "13351757f9927c3618ecb743addb5a351b91b863" }
everestrs-build = { git = "https://github.com/qwello/everest-framework.git", rev = "13351757f9927c3618ecb743addb5a351b91b863" }
